### ISSUE TITLE
Option to focus on black chords

### ISSUE THREAD

**Issue by samspineai** [pganssle/cim#19]
It would be nice to be able to focus on just the black chords to ensure sufficient practice after mastering the white chords.

**Comment by pganssle** [comment]
I think this is basically #12, right?

I think we'll need #12 anyway if we are going to support the full suite of black chord inversions, so I'm thinking there will be the regular mode, and then a "free chord choice" mode where you tell it how many chords to show and which ones to choose from, and it shows you a random assortment of those. For example, if you told it to show you just the black chords and 2 of the inversions for the black chords, and said to show 5, it would pick 1 chord as the "correct" chord, then 4 decoy chords from the array.

That said, I have found that the automatic re-weighting does a pretty good job of de-emphasizing chords you already know. My son is on purple now, but the only chord that gives him trouble is orange (he usually confuses it with green). When I do it with him, it's mostly green, orange and purple, and probably 1-2 of each of the other chords per 30-chord session. I would expect the same thing to work fine with the black chords — whichever one your child is struggling with should be weighted most heavily in the selection.

**Comment by samspineai** [comment]
Yes, you are right. #12 covers this and the reweighting does seem to be working well. It probably makes sense to close this one then.
